# Generated by Django 5.1.15 on 2026-07-03 08:13

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corpus', '0001_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_copyright', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'corpora',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'running'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='running', max_length=16)),
                ('git_commit', models.CharField(blank=True, max_length=64)),
                ('corpora_path', models.CharField(blank=True, max_length=512)),
                ('corpora_ingested', models.JSONField(blank=True, default=list)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('iso639_3', models.CharField(db_index=True, max_length=8)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Morpheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morpheme_xml_id', models.CharField(max_length=256)),
                ('position', models.IntegerField()),
                ('morpheme_class', models.CharField(blank=True, max_length=64)),
                ('sclass', models.CharField(blank=True, max_length=64)),
                ('form_original', models.TextField(blank=True)),
                ('form_standard', models.TextField(blank=True)),
                ('form_alternate', models.TextField(blank=True)),
                ('phon_original', models.TextField(blank=True)),
                ('phon_standard', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['word', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Dialect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('official_name', models.CharField(blank=True, max_length=128)),
                ('chinese_name', models.CharField(blank=True, max_length=128)),
                ('glottocode', models.CharField(blank=True, max_length=32)),
                ('other_names', models.CharField(blank=True, max_length=256)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialects', to='corpus.language')),
            ],
            options={
                'ordering': ['language__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_xml_id', models.CharField(max_length=256)),
                ('source_path', models.CharField(max_length=512)),
                ('xml_lang', models.CharField(max_length=16)),
                ('citation', models.TextField(blank=True)),
                ('bibtex_citation', models.TextField(blank=True)),
                ('copyright', models.TextField(blank=True)),
                ('source', models.TextField(blank=True)),
                ('audio_mode', models.CharField(blank=True, max_length=32)),
                ('glottocode', models.CharField(blank=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='corpus.corpus')),
                ('dialect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='texts', to='corpus.dialect')),
                ('ingestion_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texts', to='corpus.ingestionrun')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='texts', to='corpus.language')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_xml_id', models.CharField(max_length=256)),
                ('position', models.IntegerField()),
                ('form_original', models.TextField(blank=True)),
                ('form_standard', models.TextField(blank=True)),
                ('form_alternate', models.TextField(blank=True)),
                ('phon_original', models.TextField(blank=True)),
                ('phon_standard', models.TextField(blank=True)),
                ('token_count', models.IntegerField(default=0)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='corpus.text')),
            ],
            options={
                'ordering': ['text', 'position'],
            },
        ),
        migrations.CreateModel(
            name='TextAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(blank=True, max_length=512)),
                ('url', models.URLField(blank=True, max_length=1024)),
                ('start', models.FloatField(blank=True, null=True)),
                ('end', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=256)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='corpus.text')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_xml_id', models.CharField(max_length=256)),
                ('position', models.IntegerField()),
                ('word_class', models.CharField(blank=True, max_length=64)),
                ('sclass', models.CharField(blank=True, max_length=64)),
                ('form_original', models.TextField(blank=True)),
                ('form_standard', models.TextField(blank=True)),
                ('form_alternate', models.TextField(blank=True)),
                ('phon_original', models.TextField(blank=True)),
                ('phon_standard', models.TextField(blank=True)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='corpus.sentence')),
            ],
            options={
                'ordering': ['sentence', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_lang', models.CharField(blank=True, max_length=16)),
                ('kind_of', models.CharField(blank=True, max_length=32)),
                ('ver', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('text_norm', models.TextField(blank=True)),
                ('morpheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='corpus.morpheme')),
                ('sentence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='corpus.sentence')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='corpus.word')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('surface_original', models.TextField(blank=True)),
                ('surface_standard', models.TextField(blank=True)),
                ('surface_norm', models.TextField()),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='corpus.corpus')),
                ('dialect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='corpus.dialect')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='corpus.language')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='corpus.sentence')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='corpus.word')),
            ],
            options={
                'ordering': ['sentence', 'position'],
            },
        ),
        migrations.AddField(
            model_name='morpheme',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morphemes', to='corpus.word'),
        ),
        migrations.CreateModel(
            name='AudioSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(blank=True, max_length=512)),
                ('url', models.URLField(blank=True, max_length=1024)),
                ('start', models.FloatField(blank=True, null=True)),
                ('end', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=256)),
                ('morpheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_segments', to='corpus.morpheme')),
                ('sentence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_segments', to='corpus.sentence')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_segments', to='corpus.word')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dialect',
            constraint=models.UniqueConstraint(fields=('language', 'name'), name='uniq_dialect_per_language'),
        ),
        migrations.AddIndex(
            model_name='text',
            index=models.Index(fields=['corpus', 'language'], name='corpus_text_corpus__bd52c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='text',
            constraint=models.UniqueConstraint(fields=('corpus', 'text_xml_id'), name='uniq_text_per_corpus'),
        ),
        migrations.AddIndex(
            model_name='sentence',
            index=models.Index(fields=['text', 'position'], name='corpus_sent_text_id_d138d1_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['sentence', 'position'], name='corpus_word_sentenc_a8147e_idx'),
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['xml_lang'], name='corpus_tran_xml_lan_1f2f08_idx'),
        ),
        migrations.AddIndex(
            model_name='translation',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text_norm'], name='translation_text_norm_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('morpheme__isnull', True), ('sentence__isnull', False), ('word__isnull', True)), models.Q(('morpheme__isnull', True), ('sentence__isnull', True), ('word__isnull', False)), models.Q(('morpheme__isnull', False), ('sentence__isnull', True), ('word__isnull', True)), _connector='OR'), name='translation_exactly_one_owner'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['surface_norm'], name='corpus_toke_surface_55b603_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['language', 'surface_norm'], name='corpus_toke_languag_c3a578_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=django.contrib.postgres.indexes.GinIndex(fields=['surface_norm'], name='token_surface_norm_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['sentence', 'position'], name='corpus_toke_sentenc_c7ba3c_idx'),
        ),
        migrations.AddIndex(
            model_name='morpheme',
            index=models.Index(fields=['word', 'position'], name='corpus_morp_word_id_0bac66_idx'),
        ),
        migrations.AddConstraint(
            model_name='audiosegment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('morpheme__isnull', True), ('sentence__isnull', False), ('word__isnull', True)), models.Q(('morpheme__isnull', True), ('sentence__isnull', True), ('word__isnull', False)), models.Q(('morpheme__isnull', False), ('sentence__isnull', True), ('word__isnull', True)), _connector='OR'), name='audiosegment_exactly_one_owner'),
        ),
    ]
