# Generated by Django 5.1.15 on 2026-07-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='audio_mode',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
