# Generated by Django 5.1.15 on 2026-07-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_alter_text_audio_mode'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='text',
            name='uniq_text_per_corpus',
        ),
        migrations.AddIndex(
            model_name='text',
            index=models.Index(fields=['text_xml_id'], name='corpus_text_text_xm_2d1dc1_idx'),
        ),
        migrations.AddConstraint(
            model_name='text',
            constraint=models.UniqueConstraint(fields=('corpus', 'source_path'), name='uniq_text_per_corpus_path'),
        ),
    ]
