"""Public API capacity limits for the small Lightsail service."""

QUERY_MAX_CHARS = 2_048
SEARCH_PAGE_MAX_ROWS = 1_000
SUMMARY_MAX_ROWS = 1_000
DATASET_PREVIEW_MAX_ROWS = 250
DATASET_EXPORT_MAX_ROWS = 100_000
DEFAULT_SQLITE_PROGRESS_CALLBACKS = 2_000_000
DEFAULT_REQUESTS_PER_MINUTE = 60
DEFAULT_REQUEST_BURST = 20
DEFAULT_EXPORTS_PER_MINUTE = 5
DEFAULT_EXPORT_BURST = 5
DEFAULT_QUERY_CONCURRENCY = 4
